spring.application.name=museo-elder-backend
server.port=8084
server.address=0.0.0.0

# CORS abierto para pruebas (ajústalo en despliegue)
app.cors.allowed-origins=*
app.cors.allowed-methods=GET,POST,OPTIONS
app.cors.allowed-headers=*

spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
